### ISSUE TITLE
cilk statements require a complete env in order to compute cilkFrameDeclsScopes

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC-cilk#3]
Basically, computing `cilkFrameDeclsScopes` happens via forward, requiring the `env` to be specified.  `body` may include some cilk extension constructs which expect there to be some additional things in the `env` such as a misc item indicating the type of clone, and the struct declaration that we are currently constructing.  If we tried to actually add this decl to the environment used in this decoration of `body`, it would be a circular dependency, but without it `body` (rightfully) contains errors due to contained cilk sync/spawn/return statements forwarding to something referencing an undefined struct.  

This error only shows up when integrating with other extensions, when something else checks for errors prior to forwarding.  Thus the tests in this extension pass, but the ableC_sample_projects test that integrates with the datatypes extension crashes.  It is only showing up on the feature/env branch because of some slight changes to host flow types that is now demanding something that wasn't being demanded previously.  

My advice for fixing this is to have cilk spawn/return/sync/etc. statements check for the presence of the misc env flags, and if neither one is present then forward to `nullStmt()` (or maybe to `warnStmt` with any errors from children) silently without raising any (additional) errors.  This shouldn't be too major of a change, but I just don't have time to fix this right now.  

(Also to be clear, this is *not* an interference problem - it's just a bug in the extension.)  

@TravisCarlson can you please take a look at this soonish?  Thanks

**Comment by TravisCarlson** [comment]
Hi @krame505 ,

Is this (953dd88) what you're suggesting? I was confused by your adding of the slow clone miscItem in `makeFrame`. Your description of the issue seemed to suggest that wouldn't be set.

- Travis

**Comment by krame505** [comment]
Yes, I think so... I meant to change that line back, sorry.  
Thanks!

**Comment by ericvanwyk** [comment]
So I guess this is sorted out.  @krame505 - does this mean you can merge your environment stuff now?

**Comment by krame505** [comment]
Yes, I did a couple of days ago.

**Comment by ericvanwyk** [comment]
Great - it has been a busy week so I'm just now trying to catch up on this.
