### ISSUE TITLE
This project's makefiles do not work the same as other ableC extensions

### ISSUE THREAD

**Issue by tedinski** [melt-umn/ableC-cilk#4]
We should homogenize it. It caused a broken Jenkins builds because it didn't spot `ABLEC_BASE` like all the other makefiles do.

**Comment by tedinski** [comment]
@TravisCarlson would you have a chance to take care of this?

Otherwise, it'll probably be until next week when I'd get around to it.

**Comment by krame505** [comment]
I'll take a stab at it, since this is effectively blocking Silver builds from finishing on Jenkins right now, and I don't want to keep waiting on merging the reflection branch.

**Comment by krame505** [comment]
Fixed.

**Comment by tedinski** [comment]
Reopening. I think you've only changed the top-level makefile?

Likely, this accidentally worked again, because your change caused it to checkout ableC locally when it built this particular job. But then, the subsequent builds from ableC upstream would have re-used the workspace and erroneously re-used the local checkout and not `ABLEC_BASE` of upstream.

**Comment by krame505** [comment]
Oh, I just tried changing the top one and it worked, so I didn't bother to commit the changed examples Makefile.  I'll go and do that...

**Comment by tedinski** [comment]
I mean, probably all 3 sub makefiles need updating.

Can probably test locally by moving the dir so it's not next to ablec and trying all the make targets while having `ABLEC_BASE` set correctly

**Comment by krame505** [comment]
The test makefile was already modern, I forgot about the analyses one.  Just a min.

**Comment by krame505** [comment]
Done, go ahead and close this if it looks good.
